USD_STAGE_MENU_ITEM   =   "USD Stage..."
USD_STAGE_TOOLTIP = "Create a USD Stage from File"
USD_EXPLORER_MENU_ITEM   =   "USD Explorer..."
USD_EXPLORER_TOOLTIP = "Opens the USD Explorer"
USD_LAYER_EDITOR_MENU_ITEM = "USD Layer Editor..."
USD_LAYER_EDITOR_TOOLTIP = "Opens the USD Layer Editor"