name: Pre-flight build on pull request

# Trigger the workflow on pull request (assigned) event for the branch
# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    branches: [main]
    types:    [assigned]

jobs:

  clang_format_linter:
      timeout-minutes: 30
      runs-on: ubuntu-latest
      # Start clang format by assigning pull-request to yourself.
      if: ${{ github.event.assignee.login == github.event.pull_request.user.login }}
      steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: '.'
          clangFormatVersion: 17
